### ISSUE TITLE
Pyinstaller

### ISSUE THREAD

**Issue by kenan3507** [HugoLB0/Ransom0#10]
What could be the reason that it does not work after compiling with pyinstaller?

**Comment by HugoLB0** [comment]
Hi, I'm not quite sure what's the issue, maybe it's caused by Tkinter, I’m still testing it on different platform. Maybe can you provide me a little more information? About the platform and which option did you use (like --noconsole ).

**Comment by kenan3507** [comment]
I'm pretty new to Python ,

 i did it like this 

pyinstaller payloadname.py --onefile --noconsole

**Comment by kenan3507** [comment]
I guess I shouldn't have typed --noconsole

**Comment by kenan3507** [comment]
I tried it on 2 separate Windows 10 computers. It works fine as a Python script. But when I compile with pyinstaller, tkinter interface does not work although it saves logs without any problems.

I tried many settings but somehow did not happen.

Maybe there is something I missed?
