### ISSUE TITLE
NGROK PROBLEM TO RECEIVE 

### ISSUE THREAD

**Issue by SexureCode** [HugoLB0/Ransom0#12]
POST /                         502 Bad Gateway

i get this error after i run it .

**Comment by SexureCode** [comment]
Unable to receive key  from the server and cant get the decrypted key in database.Help me pls homie

**Comment by SexureCode** [comment]
Unable to decrypt using the received key .

**Comment by HugoLB0** [comment]
Hi, can u provide me more details pls. Thanks

**Comment by SexureCode** [comment]
Hey bro, i managed to generate the key .And succesfully connected database.But unfortunately the key is not working and 1 more thing is the generated key info ,id,date columns not receiving in database.Can you help me figured this out ?Thanks .

**Comment by HugoLB0** [comment]
> Hey bro, i managed to generate the key .And succesfully connected database.But unfortunately the key is not working and 1 more thing is the generated key info ,id,date columns not receiving in database.Can you help me figured this out ?Thanks .

Mhm I never had this issue before. Did you followed the instructions in the README.md ? especially the part when you need to copy the database link into ransom0.py . I'll make some testing, but try again, start from scratch, delete the logs and everything.

**Comment by SexureCode** [comment]
Thanks for replying HugoLB0. I will test again and let you know.
